### ISSUE TITLE
Visibility of data types. 

### ISSUE THREAD

**Issue by Shimuuar** [ergoplatform/sigma-rust#307]
Few questions arising from attempt to parse transactions from blockchain:

1. `pub struct ValId(u32)` has private field and no accessors. Since there're no contraints on value of underlying `u32` I think field should be just made public.

2. Is there reason to include `pub struct SigmaProp(SigmaBoolean)`? Naively plain `SigmaBoolean` would work as well.

3. `ergotree_ir::mir::constant::ConstantPlaceholder` is only visible to crate. Since it's part of `Expr` I believe it's an oversight.

**Comment by greenhat** [comment]
> Few questions arising from attempt to parse transactions from blockchain:
> 
> 1. `pub struct ValId(u32)` has private field and no accessors. Since there're no contraints on value of underlying `u32` I think field should be just made public.

I agree. I did not make it public initially because it's a signed int in Scala, so technically, there are constraints (0..=i32::MAX) but I think it's safe to ignore them for now.

> 2. Is there reason to include `pub struct SigmaProp(SigmaBoolean)`? Naively plain `SigmaBoolean` would work as well.

I modeled it after Scala's `SigmaProp` interface - https://github.com/ScorexFoundation/sigmastate-interpreter/blob/89afefa935d52dd83741f6530f97e4c935992f76/sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala#L59-L100
There will be more methods added later. Although they probably could be added directly to the `SigmaBoolean` I'd rather stick with `SigmaProp` to keep it in sync with the Scala version.

> 3. `ergotree_ir::mir::constant::ConstantPlaceholder` is only visible to crate. Since it's part of `Expr` I believe it's an oversight.

Yep, I agree.
