### ISSUE TITLE
[300 SigmaUSD] Integration testing suite for P2P networking

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/sigma-rust#480]
### Motivation
- To test our implementation of P2P networking against the reference implementation in Scala.
- To catch regressions introduced during the development.

### Implementation options
The idea is to test P2P requests and responses against running ergo node built from the master branch https://github.com/ergoplatform/ergo
In our tests, we should connect to the node and run our scenarios. Ideally, we want to make tests stateless, i.e. tests should not depend on changes to the node's state made in other tests. Although we can ignore it for now due to initial ergo-p2p requests being intended for the SPV node and does not change the node's state. In the future when we implement P2P requests that change the node's state we'd want them to be stateless. So it makes sense to lay the foundation for it now.

Possible options to run ergo node:
### 1. Launch as a standalone application
Launch the node as usual, let it sync with the mainnet, and then kill it after our tests are done.
Cons:
- wasting mainnet nodes resources;
- risk of banning by github since running nodes are against github actions TOS;

### 2. Run node's integration test
Create a special integration test that starts the node in its own net in mining (block generation) mode. This test can be then called via `sbt it:test [name]` command.

See the example of ergo integration test - https://github.com/ergoplatform/ergo/blob/95139ec990fc91f8f4c70a61468edf8834143329/src/it/scala/org/ergoplatform/it/NodeRecoverySpec.scala#L14-L53

Clearly, we want the second option, i.e. run the node via its own integration test. Also, it fits into the future stateless tests requirement, where we just launch the node via its own integration test for any of our single tests.

### Todo
- Write an integration test in ergo node to run it in our tests;
- Establish GA workflow for p2p integration tests;

**Comment by kettlebell** [comment]
Starting this one.

**Comment by kettlebell** [comment]
Ran into some strange issues with trying to get this running with just your referenced test `NodeRecoverySpec`. I figured out how to filter out particular tests, it looks like `sbt -Denv=test clean "it:testOnly *NodeRecoverySpec"`. It's essential to have the double quotes.

Now running this in CI (where the initial setup was copied from the original repo) gives the following error about having no docker image: https://github.com/ergoplatform/sigma-rust/runs/4770882304?check_suite_focus=true#step:5:594

Now if we do away with the filtering and run every test, `NodeRecoverySpec` also fails: https://github.com/ergoplatform/sigma-rust/runs/4757818623?check_suite_focus=true#step:5:81292

Have you run into errors like this?

Another weird thing happens when running the tests locally on my ubuntu box. For `NodeRecoverySpec`, the node never ends up mining a single block, resulting in a timeout of the test.

**Comment by greenhat** [comment]
It looks like using a docker in the job step might not be a good idea after all. The node integration tests (`it:tests`) we're planned to run on our own Jenkins instance and might be too much for GA job step (docker-wise). I have a feeling that maybe we are re-inventing the wheel and https://docs.github.com/en/actions/using-containerized-services/about-service-containers might be a better approach. If I squint enough I can see how our node plays the same role as Redis/Postgres in other apps. If we could publish a container that builds and runs node from the master branch configured for our tests.

**Comment by kettlebell** [comment]
Revisiting this task, I see that official ergo node images are published at https://hub.docker.com/r/ergoplatform/ergo/tags. Can we use these in 'devnet' mode, and pull down the image in a service container?

**Comment by greenhat** [comment]
> Revisiting this task, I see that official ergo node images are published at https://hub.docker.com/r/ergoplatform/ergo/tags. Can we use these in 'devnet' mode, and pull down the image in a service container?

That'd be great! We want to start the node in "start new blockchain and mine new blocks at 1 block/s rate" kind of setup.

**Comment by kettlebell** [comment]
Got it running in devnet mode locally with docker. Despite setting `blockInterval = 1m` under `chain` in the `conf` file, I can see that it mines a block every 5 seconds. I tried bumping up `initialDifficultyHex` but it looked to make no difference (if you put in too-large a value the node crashes saying it can't parse the hex-value). Is this ok?

Another thing I noticed is that the node won't start with the following setting (which I just took from https://github.com/ergoplatform/ergo/blob/master/src/test/resources/application.conf):
```
scorex {
  restApi {
    apiKeyHash = null
  }
}
```

The node insists on a value for `apiKeyHash`. Do we need a specific value here?

**Comment by greenhat** [comment]
> Got it running in devnet mode locally with docker. Despite setting `blockInterval = 1m` under `chain` in the `conf` file, I can see that it mines a block every 5 seconds. I tried bumping up `initialDifficultyHex` but it made no difference (if you put in too-large a value the node crashes saying it can't parse the hex-value). Is this ok?

Yes, the 5-sec interval is actually very good. By the time our tests start we want at least a couple of blocks in the chain. So, 1 min is too much anyway.
 
> Another thing I noticed is that the node won't start with the following setting (which I just took from https://github.com/ergoplatform/ergo/blob/master/src/test/resources/application.conf):
> 
> ```
> scorex {
>   restApi {
>     apiKeyHash = null
>   }
> }
> ```
> 
> The node insists on a value for `apiKeyHash`. Do we need a specific value here?

It's essentially a password for the sensitive part of the node REST API (wallet, etc.). You can use "hello" from 
https://github.com/ergoplatform/ergo/blob/f38f3a6d0ab8849871adc54010846c5afb101ff4/src/main/resources/mainnet.conf#L72-L75

**Comment by kettlebell** [comment]
Guys sorry about the notification spam from all my commits. I'm wrestling with Github Actions. I wish I could test things locally.

**Comment by greenhat** [comment]
No worries! And FWIW I got only commits notifications. If you're talking about CI notifications I believe only commit author gets them.

**Comment by kettlebell** [comment]
That's good to know, thanks!

**Comment by kettlebell** [comment]
I've got a working service container running an Ergo node in `devnet` mode. The WASM test for `/info` endpoint also passes, successfully requesting from the spawned node. There are a couple of issues that we need to address:
- Service containers currently don't allow us to specify arguments to the ENTRYPOINT of the container (`java -jar ergo.jar ...`). We need to supply the following args for our node: `--devnet -c /etc/myergo.conf`. As a temporary workaround I've made a wrapping docker container here: https://hub.docker.com/r/kbell1234/ergo_node_devnet. The `Dockerfile` is very simple:
  ```
    FROM ergoplatform/ergo:latest
    EXPOSE 9020 9052 9030 9053
    WORKDIR /home/ergo
    VOLUME ["/home/ergo/.ergo"]
    COPY ergo.conf /etc/myergo.conf
    ENTRYPOINT ["java", "-jar", "/home/ergo/ergo.jar", "--devnet", "-c", "/etc/myergo.conf"]
  ```
  - Notice how I copied in `ergo.conf` within the Dockerfile. It turns out that service containers are initialized before all job steps, so we can't copy in the file from the repo external to the Dockerfile.
  - I see that docker images are automatically created and pushed on every new version of the ergo reference implementation. Perhaps we can hook into that to create an image with the above Dockerfile?
- Github Actions restricts the use of service containers to `ubuntu-latest` job runners. This is going to cause a problem for swift integration tests. We can use swift under linux runners (e.g. using https://github.com/fwal/setup-swift) but we need recent versions macOS for the async features. Until the linux versions catch up, maybe it's simpler to hit the hard-coded node for our tests.

**Comment by greenhat** [comment]
> I've got a working service container running an Ergo node in `devnet` mode. The WASM test for `/info` endpoint also passes, successfully requesting from the spawned node. There are a couple of issues that we need to address:

Awesome!

> 
> * Service containers currently don't allow us to specify arguments to the ENTRYPOINT of the container (`java -jar ergo.jar ...`). We need to supply the following args for our node: `--devnet -c /etc/myergo.conf`. As a temporary workaround I've made a wrapping docker container here: https://hub.docker.com/r/kbell1234/ergo_node_devnet. The `Dockerfile` is very simple:
>   ```
>     FROM ergoplatform/ergo:latest
>     EXPOSE 9020 9052 9030 9053
>     WORKDIR /home/ergo
>     VOLUME ["/home/ergo/.ergo"]
>     COPY ergo.conf /etc/myergo.conf
>     ENTRYPOINT ["java", "-jar", "/home/ergo/ergo.jar", "--devnet", "-c", "/etc/myergo.conf"]
>   ```
>   
>   * Notice how I copied in `ergo.conf` within the Dockerfile. It turns out that service containers are initialized before all job steps, so we can't copy in the file from the repo external to the Dockerfile.
>   * I see that docker images are automatically created and pushed on every new version of the ergo reference implementation. Perhaps we can hook into that to create an image with the above Dockerfile?

Yes, sounds good. Could you please make a PR?

> * Github Actions restricts the use of service containers to `ubuntu-latest` job runners. This is going to cause a problem for swift integration tests. We can use swift under linux runners (e.g. using https://github.com/fwal/setup-swift) but we need a recent version of macOS for the async features. Until the linux versions catch up, maybe it's simpler to hit the hard-coded node for our tests.

Oh, no problem here. I believe the latest Swift on Linux runs async/await.

**Comment by kettlebell** [comment]
> Yes, sounds good. Could you please make a PR?

Sure, will do.

> Oh, no problem here. I believe the latest Swift on Linux runs async/await.

Yes, async appears to be fine under `ubuntu-latest` runner. I've still commented out the code for the async swift test because there's a compilation error for `RestNodeApi::getInfoAsync` (line 38, I believe). I can't debug it because my mac is too old to be upgraded to macOS 12. But the other tests pass.

**Comment by kettlebell** [comment]
Got a new mac and fixed the async issue.

**Comment by greenhat** [comment]
> Got a new mac and fixed the async issue.

Great! I appreciate you're working on this!

**Comment by kettlebell** [comment]
@greenhat @kushti: v4.0.25 of the reference node published but the integration test docker image failed again: https://github.com/ergoplatform/ergo/runs/5737076427?check_suite_focus=true#step:7:107

I tracked down the problem and there's a limitation with [docker/build-push-action](https://github.com/docker/build-push-action#git-context) that prevents CI from setting a subdirectory as a context for a new image:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/791016/160748016-c7401651-3d18-462f-a2d3-c3b8fd5a4c07.png">

I don't see how we can get this working within the `/ergo` repo. Perhaps we can make a new repo under `ergoplatform` just to publish this image? I'll be happy to maintain it to keep it in sync with the ergo reference version.

**Comment by greenhat** [comment]
> @greenhat @kushti: v4.0.25 of the reference node published but the integration test docker image failed again: https://github.com/ergoplatform/ergo/runs/5737076427?check_suite_focus=true#step:7:107
> 
> I tracked down the problem and there's a limitation with [docker/build-push-action](https://github.com/docker/build-push-action#git-context) that prevents CI from setting a subdirectory as a context for a new image:
> 
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/791016/160748016-c7401651-3d18-462f-a2d3-c3b8fd5a4c07.png">
> 
> I don't see how we can get this working within the `/ergo` repo. Perhaps we can make a new repo under `ergoplatform` just to publish this image? I'll be happy to maintain it to keep it in sync with the ergo reference version.

Sounds good! Let me make the repo and give you the access. Any ideas, how to name it? `ergo-node-for-sigma-rust-integration-tests` is way too long. :)

**Comment by kettlebell** [comment]
Yeah, it's a bit tricky to name this! How about just `ergo-devnet`? Devnet mode is the only distinguishing feature of the image. I'll add an explanation to the repo.

**Comment by kettlebell** [comment]
Or, `ergo-devnet-docker`.

**Comment by greenhat** [comment]
The bounty is sent. Thank you!
